// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722154728_AddEntities")]
    partial class AddEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FT01", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C001")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT01");
                });

            modelBuilder.Entity("Domain.Entities.FT02", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT02");
                });

            modelBuilder.Entity("Domain.Entities.FT03", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Auto")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Door1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Door2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Door3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Door4")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Door5")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Door6")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Doorlock1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Doorlock2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Doorlock3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Doorlock4")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Doorlock5")
                        .HasColumnType("bit");

                    b.Property<bool?>("Close_Doorlock6")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DC1_Over")
                        .HasColumnType("bit");

                    b.Property<bool?>("DC1_Running")
                        .HasColumnType("bit");

                    b.Property<bool?>("DC2_Over")
                        .HasColumnType("bit");

                    b.Property<bool?>("DC2_Running")
                        .HasColumnType("bit");

                    b.Property<bool?>("DC3_Over")
                        .HasColumnType("bit");

                    b.Property<bool?>("DC3_Running")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_Aperture")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_PressureHigh")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door1_PressureLow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_Aperture")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_PressureHigh")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door2_PressureLow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_Aperture")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_PressureHigh")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door3_PressureLow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_Aperture")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_PressureHigh")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door4_PressureLow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_Aperture")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_PressureHigh")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door5_PressureLow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_Aperture")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_PressureHigh")
                        .HasColumnType("bit");

                    b.Property<bool?>("Door6_PressureLow")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock1_1Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock1_1Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock1_2Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock1_2Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock1_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock1_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock2_1Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock2_1Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock2_2Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock2_2Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock2_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock2_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock3_1Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock3_1Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock3_2Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock3_2Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock3_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock3_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock4_1Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock4_1Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock4_2Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock4_2Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock4_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock4_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock5_1Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock5_1Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock5_2Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock5_2Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock5_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock5_Opening")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock6_1Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock6_1Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock6_2Close")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock6_2Open")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock6_Closing")
                        .HasColumnType("bit");

                    b.Property<bool?>("Doorlock6_Opening")
                        .HasColumnType("bit");

                    b.Property<int?>("Fllow_BenSuc")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_DauTieng")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Door1")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Door2")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Door3")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Door4")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Door5")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Door6")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_Ho")
                        .HasColumnType("int");

                    b.Property<int?>("Fllow_SonDai")
                        .HasColumnType("int");

                    b.Property<bool?>("HT_Cylinder1_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder1_2")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder2_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder2_2")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder3_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder3_2")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder4_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder4_2")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder5_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder5_2")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder6_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("HT_Cylinder6_2")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("Local")
                        .HasColumnType("bit");

                    b.Property<bool?>("Local_Stop")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Man")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Door1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Door2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Door3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Door4")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Door5")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Door6")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Doorlock1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Doorlock2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Doorlock3")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Doorlock4")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Doorlock5")
                        .HasColumnType("bit");

                    b.Property<bool?>("Open_Doorlock6")
                        .HasColumnType("bit");

                    b.Property<bool?>("Remote")
                        .HasColumnType("bit");

                    b.Property<bool?>("Run_Pump1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Run_Pump2")
                        .HasColumnType("bit");

                    b.Property<bool?>("Run_Pump3")
                        .HasColumnType("bit");

                    b.Property<int?>("Setting_Door1_Aperture")
                        .HasColumnType("int");

                    b.Property<int?>("Setting_Door2_Aperture")
                        .HasColumnType("int");

                    b.Property<int?>("Setting_Door3_Aperture")
                        .HasColumnType("int");

                    b.Property<int?>("Setting_Door4_Aperture")
                        .HasColumnType("int");

                    b.Property<int?>("Setting_Door5_Aperture")
                        .HasColumnType("int");

                    b.Property<int?>("Setting_Door6_Aperture")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Stop_Remote")
                        .HasColumnType("bit");

                    b.Property<int?>("Temp_Oil")
                        .HasColumnType("int");

                    b.Property<int?>("Total_Fllow")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT03");
                });

            modelBuilder.Entity("Domain.Entities.FT05", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ACK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ACKDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Actived")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("OvenId")
                        .HasColumnType("int");

                    b.Property<string>("OvenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seconds")
                        .HasColumnType("int");

                    b.Property<double>("Setpoint")
                        .HasColumnType("float");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT05");
                });

            modelBuilder.Entity("Domain.Entities.FT06", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT06");
                });

            modelBuilder.Entity("Domain.Entities.MstUserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MstUserSettings");
                });

            modelBuilder.Entity("Domain.Entities.Permissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.RefreshTokens", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Activated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshToken");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.RoleToPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermisionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermisionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleToPermission");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
