// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251028023554_updateEntityFT08")]
    partial class updateEntityFT08
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FT01", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C001")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT01");
                });

            modelBuilder.Entity("Domain.Entities.FT02", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT02");
                });

            modelBuilder.Entity("Domain.Entities.FT03", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("API_ChanDap")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_DM_HoDT")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_DM_HoDT_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_Doi95")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_Doi95_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_DongBan")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_DongBan_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_KaTum")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_KaTum_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_LocNinh")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_LocNinh_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_LocThanh")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_LocThanh_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_LocThien")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_LocThien_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_MinhHoa")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_MinhHoa_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_MinhTam")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_MinhTam_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanHa")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanHa_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanHoa1")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanHoa1_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanHoa2")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanHoa2_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanThanh")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_TanThanh_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_ThanhLuong")
                        .HasColumnType("float");

                    b.Property<double?>("API_D_ThanhLuong_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_BenSuc")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_BinhNham")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_BinhNham2")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_DauTieng")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_HL_TXL")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_SonDai")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_TL_CDD")
                        .HasColumnType("float");

                    b.Property<double?>("API_ThanhAn")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Door1_Aperture")
                        .HasColumnType("float");

                    b.Property<double?>("Door1_Aperture_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Door1_Aperture_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Door2_Aperture")
                        .HasColumnType("float");

                    b.Property<double?>("Door2_Aperture_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Door2_Aperture_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door1")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door2")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door2_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Ho")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Ho_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Ho_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_1")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_2")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_2_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_1")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_2")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_2_Offset")
                        .HasColumnType("float");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LogBaseInterval")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Pressure_Oil_Door1")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door2")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door2_Offset")
                        .HasColumnType("float");

                    b.Property<double>("Q_cs1")
                        .HasColumnType("float");

                    b.Property<double>("Q_cs2")
                        .HasColumnType("float");

                    b.Property<double>("Q_cs3")
                        .HasColumnType("float");

                    b.Property<double>("Q_den")
                        .HasColumnType("float");

                    b.Property<double>("Q_denta")
                        .HasColumnType("float");

                    b.Property<double>("Q_di")
                        .HasColumnType("float");

                    b.Property<double?>("Q_i_1")
                        .HasColumnType("float");

                    b.Property<double?>("Q_i_2")
                        .HasColumnType("float");

                    b.Property<double>("Q_i_total")
                        .HasColumnType("float");

                    b.Property<double>("Q_tr")
                        .HasColumnType("float");

                    b.Property<double>("Q_tt")
                        .HasColumnType("float");

                    b.Property<double?>("S1_Temp_Oil")
                        .HasColumnType("float");

                    b.Property<double?>("S1_Temp_Oil_Final")
                        .HasColumnType("float");

                    b.Property<double?>("S1_Temp_Oil_Offset")
                        .HasColumnType("float");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Total_Fllow")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("W1_ho")
                        .HasColumnType("float");

                    b.Property<double>("W1_ho_old")
                        .HasColumnType("float");

                    b.Property<double>("W2_ho")
                        .HasColumnType("float");

                    b.Property<double>("W2_ho_old")
                        .HasColumnType("float");

                    b.Property<double>("W_cs1")
                        .HasColumnType("float");

                    b.Property<double>("W_cs2")
                        .HasColumnType("float");

                    b.Property<double>("W_cs3")
                        .HasColumnType("float");

                    b.Property<double>("W_den")
                        .HasColumnType("float");

                    b.Property<double>("W_di")
                        .HasColumnType("float");

                    b.Property<double>("W_tr")
                        .HasColumnType("float");

                    b.Property<double>("W_tt")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FT03");
                });

            modelBuilder.Entity("Domain.Entities.FT04", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FT04");
                });

            modelBuilder.Entity("Domain.Entities.FT05_ChartHoChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("A_VungA")
                        .HasColumnType("float");

                    b.Property<double?>("A_VungB")
                        .HasColumnType("float");

                    b.Property<double?>("A_VungC")
                        .HasColumnType("float");

                    b.Property<int?>("Index")
                        .HasColumnType("int");

                    b.Property<double?>("L_CTDD")
                        .HasColumnType("float");

                    b.Property<double?>("L_DPL")
                        .HasColumnType("float");

                    b.Property<double?>("L_DPPH")
                        .HasColumnType("float");

                    b.Property<double?>("L_HCCN")
                        .HasColumnType("float");

                    b.Property<double?>("L_MNC")
                        .HasColumnType("float");

                    b.Property<double?>("L_MNDBT")
                        .HasColumnType("float");

                    b.Property<double?>("L_MNKT")
                        .HasColumnType("float");

                    b.Property<double?>("L_MNTK")
                        .HasColumnType("float");

                    b.Property<string>("X_Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT05");
                });

            modelBuilder.Entity("Domain.Entities.FT06_InterpolationTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Col00")
                        .HasColumnType("float");

                    b.Property<double?>("Col01")
                        .HasColumnType("float");

                    b.Property<double?>("Col02")
                        .HasColumnType("float");

                    b.Property<double?>("Col03")
                        .HasColumnType("float");

                    b.Property<double?>("Col04")
                        .HasColumnType("float");

                    b.Property<double?>("Col05")
                        .HasColumnType("float");

                    b.Property<double?>("Col06")
                        .HasColumnType("float");

                    b.Property<double?>("Col07")
                        .HasColumnType("float");

                    b.Property<double?>("Col08")
                        .HasColumnType("float");

                    b.Property<double?>("Col09")
                        .HasColumnType("float");

                    b.Property<double?>("Col10")
                        .HasColumnType("float");

                    b.Property<double?>("Col11")
                        .HasColumnType("float");

                    b.Property<double?>("Col12")
                        .HasColumnType("float");

                    b.Property<double?>("Col13")
                        .HasColumnType("float");

                    b.Property<double?>("Col14")
                        .HasColumnType("float");

                    b.Property<double?>("Col15")
                        .HasColumnType("float");

                    b.Property<double?>("Col16")
                        .HasColumnType("float");

                    b.Property<double?>("Col17")
                        .HasColumnType("float");

                    b.Property<double?>("Col18")
                        .HasColumnType("float");

                    b.Property<double?>("Col19")
                        .HasColumnType("float");

                    b.Property<double?>("Col20")
                        .HasColumnType("float");

                    b.Property<double?>("Col21")
                        .HasColumnType("float");

                    b.Property<double?>("Col22")
                        .HasColumnType("float");

                    b.Property<double?>("Col23")
                        .HasColumnType("float");

                    b.Property<double?>("Col24")
                        .HasColumnType("float");

                    b.Property<double?>("Col25")
                        .HasColumnType("float");

                    b.Property<double?>("Col26")
                        .HasColumnType("float");

                    b.Property<double?>("Col27")
                        .HasColumnType("float");

                    b.Property<double?>("Col28")
                        .HasColumnType("float");

                    b.Property<double?>("Col29")
                        .HasColumnType("float");

                    b.Property<double?>("Col30")
                        .HasColumnType("float");

                    b.Property<double?>("Col31")
                        .HasColumnType("float");

                    b.Property<double?>("Col32")
                        .HasColumnType("float");

                    b.Property<double?>("Col33")
                        .HasColumnType("float");

                    b.Property<double?>("Col34")
                        .HasColumnType("float");

                    b.Property<double?>("Col35")
                        .HasColumnType("float");

                    b.Property<double?>("Col36")
                        .HasColumnType("float");

                    b.Property<double?>("Col37")
                        .HasColumnType("float");

                    b.Property<double?>("Col38")
                        .HasColumnType("float");

                    b.Property<double?>("Col39")
                        .HasColumnType("float");

                    b.Property<double?>("Col40")
                        .HasColumnType("float");

                    b.Property<double?>("Col41")
                        .HasColumnType("float");

                    b.Property<double?>("Col42")
                        .HasColumnType("float");

                    b.Property<double?>("Col43")
                        .HasColumnType("float");

                    b.Property<double?>("Col44")
                        .HasColumnType("float");

                    b.Property<double?>("Col45")
                        .HasColumnType("float");

                    b.Property<double?>("Col46")
                        .HasColumnType("float");

                    b.Property<double?>("Col47")
                        .HasColumnType("float");

                    b.Property<double?>("Col48")
                        .HasColumnType("float");

                    b.Property<double?>("Col49")
                        .HasColumnType("float");

                    b.Property<double?>("Col50")
                        .HasColumnType("float");

                    b.Property<double?>("Col51")
                        .HasColumnType("float");

                    b.Property<double?>("Col52")
                        .HasColumnType("float");

                    b.Property<double?>("Col53")
                        .HasColumnType("float");

                    b.Property<double?>("Col54")
                        .HasColumnType("float");

                    b.Property<double?>("Col55")
                        .HasColumnType("float");

                    b.Property<double?>("Col56")
                        .HasColumnType("float");

                    b.Property<double?>("Col57")
                        .HasColumnType("float");

                    b.Property<double?>("Col58")
                        .HasColumnType("float");

                    b.Property<double?>("Col59")
                        .HasColumnType("float");

                    b.Property<double?>("Col60")
                        .HasColumnType("float");

                    b.Property<double?>("Col61")
                        .HasColumnType("float");

                    b.Property<double?>("Col62")
                        .HasColumnType("float");

                    b.Property<double?>("Col63")
                        .HasColumnType("float");

                    b.Property<double?>("Col64")
                        .HasColumnType("float");

                    b.Property<double?>("Col65")
                        .HasColumnType("float");

                    b.Property<double?>("Col66")
                        .HasColumnType("float");

                    b.Property<double?>("Col67")
                        .HasColumnType("float");

                    b.Property<double?>("Col68")
                        .HasColumnType("float");

                    b.Property<double?>("Col69")
                        .HasColumnType("float");

                    b.Property<double?>("Col70")
                        .HasColumnType("float");

                    b.Property<double?>("Col71")
                        .HasColumnType("float");

                    b.Property<double?>("Col72")
                        .HasColumnType("float");

                    b.Property<double?>("Col73")
                        .HasColumnType("float");

                    b.Property<double?>("Col74")
                        .HasColumnType("float");

                    b.Property<double?>("Col75")
                        .HasColumnType("float");

                    b.Property<double?>("Col76")
                        .HasColumnType("float");

                    b.Property<double?>("Col77")
                        .HasColumnType("float");

                    b.Property<double?>("Col78")
                        .HasColumnType("float");

                    b.Property<double?>("Col79")
                        .HasColumnType("float");

                    b.Property<double?>("Col80")
                        .HasColumnType("float");

                    b.Property<double?>("Col81")
                        .HasColumnType("float");

                    b.Property<double?>("Col82")
                        .HasColumnType("float");

                    b.Property<double?>("Col83")
                        .HasColumnType("float");

                    b.Property<double?>("Col84")
                        .HasColumnType("float");

                    b.Property<double?>("Col85")
                        .HasColumnType("float");

                    b.Property<double?>("Col86")
                        .HasColumnType("float");

                    b.Property<double?>("Col87")
                        .HasColumnType("float");

                    b.Property<double?>("Col88")
                        .HasColumnType("float");

                    b.Property<double?>("Col89")
                        .HasColumnType("float");

                    b.Property<double?>("Col90")
                        .HasColumnType("float");

                    b.Property<double?>("Col91")
                        .HasColumnType("float");

                    b.Property<double?>("Col92")
                        .HasColumnType("float");

                    b.Property<double?>("Col93")
                        .HasColumnType("float");

                    b.Property<double?>("Col94")
                        .HasColumnType("float");

                    b.Property<double?>("Col95")
                        .HasColumnType("float");

                    b.Property<double?>("Col96")
                        .HasColumnType("float");

                    b.Property<double?>("Col97")
                        .HasColumnType("float");

                    b.Property<double?>("Col98")
                        .HasColumnType("float");

                    b.Property<double?>("Col99")
                        .HasColumnType("float");

                    b.Property<int?>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FT06");
                });

            modelBuilder.Entity("Domain.Entities.FT07_ChartMucNuoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BoPhai")
                        .HasColumnType("float");

                    b.Property<double?>("BoTrai")
                        .HasColumnType("float");

                    b.Property<int?>("Index")
                        .HasColumnType("int");

                    b.Property<double?>("Q2800")
                        .HasColumnType("float");

                    b.Property<double?>("Q300")
                        .HasColumnType("float");

                    b.Property<double?>("Q400")
                        .HasColumnType("float");

                    b.Property<double?>("Q600")
                        .HasColumnType("float");

                    b.Property<string>("X_Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("X_Value")
                        .HasColumnType("float");

                    b.Property<string>("Z_Thuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT07");
                });

            modelBuilder.Entity("Domain.Entities.FT08_FilesManagement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT08");
                });

            modelBuilder.Entity("Domain.Entities.MstUserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MstUserSettings");
                });

            modelBuilder.Entity("Domain.Entities.Permissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.RefreshTokens", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Activated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshToken");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.RoleToPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermisionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermisionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleToPermission");
                });

            modelBuilder.Entity("Domain.Entities.ScadaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionScada")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScadaUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
