// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250915135544_updateFT03113")]
    partial class updateFT03113
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FT01", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C001")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT01");
                });

            modelBuilder.Entity("Domain.Entities.FT02", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C000")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FT02");
                });

            modelBuilder.Entity("Domain.Entities.FT03", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("API_DM_HoDT")
                        .HasColumnType("float");

                    b.Property<double?>("API_DM_HoDT_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_Doi95")
                        .HasColumnType("float");

                    b.Property<double?>("API_Doi95_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_DongBan")
                        .HasColumnType("float");

                    b.Property<double?>("API_DongBan_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_BenSuc")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_BinhNham")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_BinhNham2")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_DauTieng")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_HL_TXL")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_SonDai")
                        .HasColumnType("float");

                    b.Property<double?>("API_Fllow_TL_CDD")
                        .HasColumnType("float");

                    b.Property<double?>("API_KaTum")
                        .HasColumnType("float");

                    b.Property<double?>("API_KaTum_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_LocNinh")
                        .HasColumnType("float");

                    b.Property<double?>("API_LocNinh_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_LocThanh")
                        .HasColumnType("float");

                    b.Property<double?>("API_LocThanh_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_LocThien")
                        .HasColumnType("float");

                    b.Property<double?>("API_LocThien_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_MinhHoa")
                        .HasColumnType("float");

                    b.Property<double?>("API_MinhHoa_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_MinhTam")
                        .HasColumnType("float");

                    b.Property<double?>("API_MinhTam_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanHa")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanHa_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanHoa1")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanHoa1_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanHoa2")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanHoa2_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanThanh")
                        .HasColumnType("float");

                    b.Property<double?>("API_TanThanh_Total")
                        .HasColumnType("float");

                    b.Property<double?>("API_ThanhLuong")
                        .HasColumnType("float");

                    b.Property<double?>("API_ThanhLuong_Total")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Door1_Aperture")
                        .HasColumnType("float");

                    b.Property<double?>("Door1_Aperture_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Door1_Aperture_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Door2_Aperture")
                        .HasColumnType("float");

                    b.Property<double?>("Door2_Aperture_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Door2_Aperture_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door1")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door2")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Door2_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Ho")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Ho_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Fllow_Ho_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_1")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_2")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder1_2_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_1")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_2")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("HT_Cylinder2_2_Offset")
                        .HasColumnType("float");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LogBaseInterval")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Pressure_Oil_Door1")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door1_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door1_Offset")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door2")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door2_Final")
                        .HasColumnType("float");

                    b.Property<double?>("Pressure_Oil_Door2_Offset")
                        .HasColumnType("float");

                    b.Property<double>("Q_cs1")
                        .HasColumnType("float");

                    b.Property<double>("Q_cs2")
                        .HasColumnType("float");

                    b.Property<double>("Q_cs3")
                        .HasColumnType("float");

                    b.Property<double>("Q_den")
                        .HasColumnType("float");

                    b.Property<double>("Q_denta")
                        .HasColumnType("float");

                    b.Property<double>("Q_di")
                        .HasColumnType("float");

                    b.Property<double?>("Q_i")
                        .HasColumnType("float");

                    b.Property<double>("Q_i_total")
                        .HasColumnType("float");

                    b.Property<double>("Q_tr")
                        .HasColumnType("float");

                    b.Property<double>("Q_tt")
                        .HasColumnType("float");

                    b.Property<double?>("S1_Temp_Oil")
                        .HasColumnType("float");

                    b.Property<double?>("S1_Temp_Oil_Final")
                        .HasColumnType("float");

                    b.Property<double?>("S1_Temp_Oil_Offset")
                        .HasColumnType("float");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("W1_ho")
                        .HasColumnType("float");

                    b.Property<double>("W1_ho_old")
                        .HasColumnType("float");

                    b.Property<double>("W2_ho")
                        .HasColumnType("float");

                    b.Property<double>("W2_ho_old")
                        .HasColumnType("float");

                    b.Property<double>("W_cs1")
                        .HasColumnType("float");

                    b.Property<double>("W_cs2")
                        .HasColumnType("float");

                    b.Property<double>("W_cs3")
                        .HasColumnType("float");

                    b.Property<double>("W_den")
                        .HasColumnType("float");

                    b.Property<double>("W_di")
                        .HasColumnType("float");

                    b.Property<double>("W_tr")
                        .HasColumnType("float");

                    b.Property<double>("W_tt")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FT03");
                });

            modelBuilder.Entity("Domain.Entities.FT04", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FT04");
                });

            modelBuilder.Entity("Domain.Entities.MstUserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MstUserSettings");
                });

            modelBuilder.Entity("Domain.Entities.Permissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.RefreshTokens", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Activated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshToken");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.RoleToPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermisionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermisionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleToPermission");
                });

            modelBuilder.Entity("Domain.Entities.ScadaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionScada")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateOperatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScadaUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
